#!/bin/bash

set -e

# make sure we are in the correct dir
if [ ! -e sites.xml.template ]; then
    echo "Please only run this script from within the workflow directory"
    exit 1
fi

# did the user specify the number of jobs
if [ "x$1" == "x" -o "x$2" == "x" -o "x$3" == "x" -o "x$4" == "x" ]; then
    echo "Please specify model, job start id, end id"
    echo "Example: ./submit run_sims_AJmodel2_chr_all.py 100 300"
    exit 1
fi

MODEL=$1
JOB_START=$2
JOB_END=$3
TOP_DIR=`pwd`
HOSTNAME=`hostname -f`

export RUN_ID=macsswig_simsaj_genome_`date +'%s'`

# where are we submitting from?
if [ -e /stash2 ]; then
    # OSG Connect
    export SUBMIT_ENV="OSG"

    module load pegasus
    module load stashcp

    export RUN_DIR=/local-scratch/$USER/workflows/$RUN_ID

elif [ "X$HOSTNAME" = "Xsubmit-4.chtc.wisc.edu" ]; then
    # Default - CondorIO from a subdir
    export SUBMIT_ENV="CHTC"

    export RUN_DIR=$PWD/runs/$RUN_ID
fi

mkdir -p $RUN_DIR

# makeing sure we have current venv
make

# we need a full tarball of the model code - ignore some dirs
echo
echo "Creating a model tarball ..."
(cd .. && tar --transform 's;^\.;model;' \
              --exclude ./workflow/macss_env.tar.gz \
              --exclude ./workflow/runs \
              -czhf $RUN_DIR/model.tar.gz . )

# generate the site catalog
SC=$RUN_DIR/sites.xml
envsubst <sites.xml.template >$SC

# generate the dax
export PYTHONPATH=`pegasus-config --python`
./tools/dax-generator $RUN_ID $RUN_DIR $MODEL $JOB_START $JOB_END
mv dax.xml $RUN_DIR/

echo
echo "An outputs directory will be created within the base of the workflow directory."
echo "Directory: $RUN_DIR/outputs"
echo

# plan and submit the  workflow
if [ "$SUBMIT_ENV" = "OSG" ]; then

    pegasus-plan \
        -Dpegasus.catalog.site.file=$SC \
        -Dpegasus.data.configuration=nonsharedfs \
        --conf pegasus.conf \
        --relative-dir $RUN_ID \
        --sites osg \
        --staging-site stash \
        --output-site local \
        --cleanup inplace \
        --dir $RUN_DIR/workflow \
        --dax $RUN_DIR/dax.xml \
        --submit
else
    pegasus-plan \
        -Dpegasus.catalog.site.file=$SC \
        -Dpegasus.data.configuration=condorio \
        --conf pegasus.conf \
        --relative-dir $RUN_ID \
        --sites condorpool \
        --output-site local \
        --cleanup inplace \
        --dir $RUN_DIR/workflow \
        --dax $RUN_DIR/dax.xml \
        --submit
fi


