#!/bin/bash

# Only run this job once to build the virtual environment

set -e

# untar prebuilt_python
tar -zxf prebuilt_python2.tar.gz

# put python in path
export PATH=$(pwd)/python2/bin:$PATH

wget https://bootstrap.pypa.io/get-pip.py
python get-pip.py

which -a pip

pip install virtualenv

virtualenv-2.7 --relocatable macss_env
. macss_env/bin/activate

pip install --upgrade pip

cd macss_env
pip install -r ../../requirements.txt
cd ..

deactivate

tar czf macss_env.tar.gz macss_env


