executable = update-virtualenv
arguments =
transfer_input_files = prebuilt_python2.tar.gz, requirements.txt
transfer_output_files = macss_env.tar.gz #is this necessary?
requirements = (OpSys == "LINUX" && OpSysMajorVer == 6)
log = update-virtualenv_$(Cluster).log
output = update-virtualenv_$(Cluster).out
error = update-virtualenv_$(Cluster).err
request_cpus = 1
request_disk = 20MB
request_memory = 20MB
queue 1