#!/bin/bash
#PBS -N macsargs2Prl
#PBS -W group_list=mfh
#PBS -q standard
#PBS -J 1-2
#PBS -l cput=280:00:00
#PBS -l walltime=10:00:00
#PBS -l select=1:ncpus=28:mem=168gb
#PBS -m abe
#PBS -M agladstein@email.arizona.edu
#PBS -l place=pack:shared
#PBS -j oe

module load python/2/2.7.11
module load parallel

cd $PBS_O_WORKDIR

PBS_ID=$(echo ${PBS_JOBID} | cut -d '[' -f1)
echo "PBS_ID: ${PBS_ID}"

JOB_ID=${PBS_ID}_${PBS_ARRAY_INDEX}
echo "JOB_ID: ${JOB_ID}"

BUCKET_OUT_PATH=/rsgrps/mfh4/Ariella/macsSwig_AJmodels_genome/model2/${PBS_ID}
echo "BUCKET_OUT_PATH: ${BUCKET_OUT_PATH}"
mkdir -p ${BUCKET_OUT_PATH}


RUN_DIR=/xdisk/agladstein/macsSwig_AJmodels

cd $RUN_DIR

#echo "seq 1 150 | parallel -j 28 /home/u15/agladstein/env/macss_env_ocelote_2.7.11/bin/python ${RUN_DIR}/gen_macsargs_AJmodel2.py $JOB_ID_{} full prior 0 ${BUCKET_OUT_PATH}"
#seq 1 150 | parallel -j 28 /home/u15/agladstein/env/macss_env_ocelote_2.7.11/bin/python ${RUN_DIR}/gen_macsargs_AJmodel2.py $JOB_ID_{} full prior 0 ${BUCKET_OUT_PATH}

echo "seq 1 28 | parallel -j 28 /home/u15/agladstein/env/macss_env_ocelote_2.7.11/bin/python ${RUN_DIR}/gen_macsargs_AJmodel2.py $JOB_ID_{} full prior 0 ${BUCKET_OUT_PATH}"
seq 1 28 | parallel -j 28 /home/u15/agladstein/env/macss_env_ocelote_2.7.11/bin/python ${RUN_DIR}/gen_macsargs_AJmodel2.py $JOB_ID_{} full prior 0 ${BUCKET_OUT_PATH}


SECOND=$(/cm/shared/apps/pbspro/current/bin/qsub -v BUCKET_OUT_PATH=$BUCKET_OUT_PATH,BUCKET_OE_PATH=$BUCKET_OE_PATH,JOB_ID=$JOB_ID_{},RUN_DIR=$RUN_DIR ${PBS_O_WORKDIR}/HPC_workflow/PBS/run-sim_model2_ocelote_standard.pbs)
echo ${SECOND}

