#!/bin/bash

set -e

TOP_DIR=$PWD

rm -rf Python-* macss_env
wget -nv https://www.python.org/ftp/python/2.7.14/Python-2.7.14.tgz
tar xzf Python-2.7.14.tgz
cd Python-2.7.14
./configure --prefix=$TOP_DIR/macss_env --disable-shared
make
make install

export PATH=$TOP_DIR/macss_env/bin:$PATH

wget -nv https://bootstrap.pypa.io/get-pip.py
python get-pip.py

which -a pip

pip install virtualenv

cd ..

#virtualenv-2.7 --relocatable macss_env
#. macss_env/bin/activate

pip install --upgrade pip==9.0.3
pip install --upgrade pip-tools

cd macss_env
pip-compile --output-file requirements.txt ../../requirements.in
pip install -r requirements.txt
cd ..

#deactivate

tar czf macss_env.tar.gz macss_env

rm -rf Python-*

